### ISSUE TITLE
Smarter lookup and compiling of build data

### ISSUE THREAD

**Issue by ryanburnette** [ryanburnette/parse-nasr-data#9]
Just running the build as an uncontrolled loop in one giant task won't be reliable.

Each airport requires two hits on external Google APIs which have rate limits that must be respected.

If any errors arise which stop the process I want to be able to pick it up where it left off.

**Comment by ryanburnette** [comment]
Currently getting this error which is probably rate limiting related.

```
ryanburnette@Red-Leader ~/D/f/parse-nasr-data> rake build > build/airports-nasr.csv                                                   master
rake aborted!
Timezone::Error::Google: Timezone::Error::Google
/Users/ryanburnette/.rvm/gems/ruby-2.3.1/gems/timezone-1.2.5/lib/timezone/lookup/google.rb:40:in `rescue in lookup'
/Users/ryanburnette/.rvm/gems/ruby-2.3.1/gems/timezone-1.2.5/lib/timezone/lookup/google.rb:25:in `lookup'
/Users/ryanburnette/.rvm/gems/ruby-2.3.1/gems/timezone-1.2.5/lib/timezone.rb:75:in `lookup'
/Users/ryanburnette/Development/far-almanac/parse-nasr-data/lib/airport.rb:42:in `timezone'
/Users/ryanburnette/Development/far-almanac/parse-nasr-data/Rakefile:26:in `block (3 levels) in <top (required)>'
/Users/ryanburnette/Development/far-almanac/parse-nasr-data/Rakefile:17:in `each'
/Users/ryanburnette/Development/far-almanac/parse-nasr-data/Rakefile:17:in `each_with_index'
/Users/ryanburnette/Development/far-almanac/parse-nasr-data/Rakefile:17:in `block (2 levels) in <top (required)>'
/Users/ryanburnette/Development/far-almanac/parse-nasr-data/Rakefile:14:in `each'
/Users/ryanburnette/Development/far-almanac/parse-nasr-data/Rakefile:14:in `block in <top (required)>'
/Users/ryanburnette/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/ryanburnette/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/ryanburnette/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Timezone::Error::Google: Timezone::Error::Google
/Users/ryanburnette/.rvm/gems/ruby-2.3.1/gems/timezone-1.2.5/lib/timezone/lookup/google.rb:35:in `lookup'
/Users/ryanburnette/.rvm/gems/ruby-2.3.1/gems/timezone-1.2.5/lib/timezone.rb:75:in `lookup'
/Users/ryanburnette/Development/far-almanac/parse-nasr-data/lib/airport.rb:42:in `timezone'
/Users/ryanburnette/Development/far-almanac/parse-nasr-data/Rakefile:26:in `block (3 levels) in <top (required)>'
/Users/ryanburnette/Development/far-almanac/parse-nasr-data/Rakefile:17:in `each'
/Users/ryanburnette/Development/far-almanac/parse-nasr-data/Rakefile:17:in `each_with_index'
/Users/ryanburnette/Development/far-almanac/parse-nasr-data/Rakefile:17:in `block (2 levels) in <top (required)>'
/Users/ryanburnette/Development/far-almanac/parse-nasr-data/Rakefile:14:in `each'
/Users/ryanburnette/Development/far-almanac/parse-nasr-data/Rakefile:14:in `block in <top (required)>'
/Users/ryanburnette/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/ryanburnette/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/ryanburnette/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => build
(See full trace by running task with --trace)
```
